; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:genericSTM32F103C8]
platform = ststm32
board = genericSTM32F103C8
framework = cmsis
build_flags = 
  -DSTM32F103xB ; Указание компилятору какую серию МК использовать.
  ;-O0 ; — Оптимизация полностью выключена. Код компилируется «в лоб», строка за строкой. Идеально для пошаговой отладки, но размер прошивки сильно вырастет.
  ;-Os ; — Оптимизация по размеру. Компилятор выкидывает дублирующиеся инструкции и оптимизирует память. Самый частый режим для микроконтроллеров.
  -O2 ; — Оптимизация по скорости. Компилятор разворачивает короткие циклы и агрессивно использует регистры процессора. Код выполняется максимально быстро, но размер Flash может увеличиться.
  ;-O3 ; — Максимальная скорость. Включает векторизацию и сильное кэширование, но код становится практически нечитаемым при отладке, а в прерываниях могут всплыть аппаратные глитчи, если где-то забыли указать volatile.

; Настройка программатора
upload_protocol = stlink
debug_tool = stlink

; Игнорируем оригинальный ID и подставляем считанный 0x046F7814
upload_flags = -c set CPUTAPID 0x2ba01477